apiVersion: v1
kind: Service
metadata:
  name: test55
  namespace: test55  # Specify the namespace
spec:
  selector:
    app: test55  # Match pods with the label app=test55
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port on the container
  type: ClusterIP  # Default service type (accessible only within the cluster)
